### ISSUE TITLE
Collections like your personal blog / site

### ISSUE THREAD

**Issue by jfmatth** [binokochumolvarghese/lightbi-hugo#12]
I love your theme, thank you.

I'm looking to break out my posts into collections like you have on your site https://binovarghese.com/, but not sure how to do that?

appreciate any help.

**Comment by binokochumolvarghese** [comment]
I am glad you liked the theme.

The `collections `is doing in the markdown with cards with top images. I will update the same shortly.

**Comment by jfmatth** [comment]
Thank you for updating your theme, but I still don't see it being similar to your site, where there are sections of posts based on (i assume) another collection tag or something?

you have Blogs / Collections / From the Desk / Codbix areas, how do i do that?

**Comment by binokochumolvarghese** [comment]
Blogs, Collections is already there. Desk is similar to collections, you can add one folder in the content section named as desk and add the __index.md_ as below.

```
---
type : "tags"
title: "The Desk"
subtitle : "Subtitle."
---
```

Update the menu also after the above.

**Comment by jfmatth** [comment]
Hi @binokochumolvarghese  thanks again for sticking with me on this :)

I'm looking for the main page to be like your personal site with 'sections' and then posts underneath that, how do i do that?

Sorry for the simple questions, I just don't use HUGO that much, but love your theme

**Comment by binokochumolvarghese** [comment]
Hi, For the sections like my personal website look of changes needed in the current theme. Mine is heavily customised according to my requirments and I am constanly rebuilding it.

I will try to implement the new features in the future relases of this theme.

**Comment by jfmatth** [comment]
Appreciate the response.

I can understand the modifications for a personal level.  

I'm assuming there is some looping on the main page, but I don't know HUGO well enough to do it myself.
