### ISSUE TITLE
Docs request: linking demo site with button

### ISSUE THREAD

**Issue by jamesbraza** [binokochumolvarghese/lightbi-hugo#17]
Hello!  This looks to be an awesome new theme.

https://themes.gohugo.io/themes/lightbi-hugo/

Are you able to add `demosite` to `theme.toml`?  That way I think a yellow "Demo" button shows up on the theme's page

<img width="240" alt="image" src="https://github.com/binokochumolvarghese/lightbi-hugo/assets/8990777/70bb1cfd-f396-4a89-af5e-ba2a4d2f95d3">

Alternate example: https://themes.gohugo.io/themes/hugo-theme-anubis/

**Comment by binokochumolvarghese** [comment]
Updated the `theme.toml`. Thank you.
