### ISSUE TITLE
Request: search integration

### ISSUE THREAD

**Issue by jamesbraza** [binokochumolvarghese/lightbi-hugo#18]
Is it possible to add support for searching of content to this theme?

For reference, here are some other Hugo themes supporting search: [PaperMod](https://github.com/adityatelange/hugo-PaperMod), [Profile](https://github.com/gurusabarish/hugo-profile), [Kross](https://github.com/themefisher/kross-hugo)

**Comment by binokochumolvarghese** [comment]
Thank you for the request, I will update you the same in the future.
