### ISSUE TITLE
Clicking #tags has extra slash in URL

### ISSUE THREAD

**Issue by jamesbraza** [binokochumolvarghese/lightbi-hugo#19]
1. Going here: https://lightbi-hugo-theme.netlify.app/notes/
2. Clicking `#tags`

![image](https://github.com/binokochumolvarghese/lightbi-hugo/assets/8990777/7158915c-efb3-4886-bd56-10bf7b84dd5b)

3. Leads to here, which has an extra slash: https://lightbi-hugo-theme.netlify.app//tags/tags/

Just fyi is all

**Comment by binokochumolvarghese** [comment]
Fixed this [704fe5f](https://github.com/binokochumolvarghese/lightbi-hugo/commit/704fe5fd293fe5c32a5b7131df8dddc671ebad40) in, thank you for notifying.
