### ISSUE TITLE
Request: experiences section

### ISSUE THREAD

**Issue by jamesbraza** [binokochumolvarghese/lightbi-hugo#20]
I would like to use Lightbi as a portfolio site theme, one feature I would like to use is support for a timeline of previous experiences.

Some examples can be found here: [Profile](https://github.com/gurusabarish/hugo-profile), [Toha](https://github.com/hugo-toha/toha), [Resume](https://github.com/eddiewebb/hugo-resume)

Thank you for your consideration!

**Comment by binokochumolvarghese** [comment]
I am sorry, this theme is designed to be blog site. This feature is bit different from the core idea and I am busy with other things.
