### ISSUE TITLE
Hardcoded values in the about page

### ISSUE THREAD

**Issue by primeroz** [binokochumolvarghese/lightbi-hugo#25]
Hi, i am very new to hugo so maybe i am missing something but if i use the `About` laytout i get hardocded values for instagra, mail and website.

https://github.com/binokochumolvarghese/lightbi-hugo/blob/master/layouts/about/about.html#L16-L33

is this expected ? is there a way to override those with my values ? 

thanks

**Comment by binokochumolvarghese** [comment]
I just removed the hardcoded values from the page. Now you can use the the [about page](https://github.com/binokochumolvarghese/lightbi-hugo/blob/master/exampleSite/content/about/_index.md) for the content and socail media links.

Hope this will solve your issue.

**Comment by primeroz** [comment]
thank you :+1:
