### ISSUE TITLE
cards show complete post, not just first lines

### ISSUE THREAD

**Issue by hanscees** [binokochumolvarghese/lightbi-hugo#28]
Hi,

when I write a long post the cards show all text and not just the first lines. Please help howto change that. 

What code goes into the post to make it  go right?

**Comment by hanscees** [comment]
Oh damn its in the front matter the description. Please add that to the archetype! 

Description  : "The Markdown Guide is a free and open-source reference guide that explains how to use Markdown, the simple and easy-to-use..."

**Comment by binokochumolvarghese** [comment]
Updated.
