### ISSUE TITLE
Some seo feedbacks

### ISSUE THREAD

**Issue by garethjax** [binokochumolvarghese/lightbi-hugo#3]
Hello nice theme,

i would like to suggest some changes:

- the title and metadescription for the home page should be defined in the config.toml, otherwise the theme uses a default value: how do you configure theme ? Could you write an example ?
- the internal pages get one of those possible values ".Description | default .Params.subtitle | default .Summary": i suggest cropping the final value to 150 characters to avoid very long descriptions. This is also useful to generate social media previews.

thanks !

**Comment by binokochumolvarghese** [comment]
Hi,
Thanks for compliment. Please find my comments:
-  Now the metadescription is the description in the post.
-  Default summary option will enable shortly.

**Comment by binokochumolvarghese** [comment]
Summary option is enabled.
