### ISSUE TITLE
[Multilingual] Default Language

### ISSUE THREAD

**Issue by yakhyadabo** [binokochumolvarghese/lightbi-hugo#31]
Hi, 

I'm deploying a multilingual website. I have the following lines in my **config.toml** to set default language to **French** (fr): 

```
defaultContentLanguage = 'fr'
defaultContentLanguageInSubdir = true

... 

[languages]
    [languages.fr]
        contentDir = 'content/fr'
        publishDir = "public/fr"
        disabled = false
        languageCode = 'fr'
... 
    [languages.en]
        contentDir = 'content/en'
        publishDir = "public/en"
        disabled = false
        languageCode = 'en'
...

```

But, unfortunately, the default is set to **English**. 

Is there any details I miss ?

**Comment by binokochumolvarghese** [comment]
In your site configuration, in the root, set:

```
defaultContentLanguage = "fr"
```

[Hugo Doc](https://gohugo.io/content-management/multilingual/#configure-languages)
