### ISSUE TITLE
How to show google slides inside post?

### ISSUE THREAD

**Issue by automataIA** [binokochumolvarghese/lightbi-hugo#4]
I try to put an iframe inside a md post, but don't work.
I have to use particular shortcodes or config in TOML file?

Furthermore, I don't have problem with other hugo theme.
Example iframe:
`<iframe src="https://docs.google.com/presentation/.........." frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>`

**Comment by binokochumolvarghese** [comment]
If you want to show inline HTML in your Markdown files, you may have to enable the unsafe mode in the config file as below:
```
[markup.goldmark.renderer]
unsafe= true
```
Please read this [release note](https://gohugo.io/news/0.60.0-relnotes/) for more information.
