### ISSUE TITLE
hello i need help

### ISSUE THREAD

**Issue by bymake** [binokochumolvarghese/lightbi-hugo#5]
I cannot display the correct abstract and the featured image for the content on the homepage, the homepage can only display the complete content of the article

**Comment by binokochumolvarghese** [comment]
I hope you are trying to display the abstract of a the blogs in the list of blog section. Fo the same you need to add the description in the front matter as below:

```
---
Title: Sample Title
Subtitle: "If you want subtitle"
Date: 2023-06-01
Lastmod : 
Tags: ["tags"]
Image: "img/sample.png"
Description: "This will shows as the abstract in the blog list."
Draft: flase
---
```

**Comment by bymake** [comment]
> I hope you are trying to display the abstract of a the blogs in the list of blog section. Fo the same you need to add the description in the front matter as below:
> 
> ```
> ---
> Title: Sample Title
> Subtitle: "If you want subtitle"
> Date: 2023-06-01
> Lastmod : 
> Tags: ["tags"]
> Image: "img/sample.png"
> Description: "This will shows as the abstract in the blog list."
> Draft: flase
> ---
> ```

thank. im go to 试试
