### ISSUE TITLE
 author key in site configuration is deprecated

### ISSUE THREAD

**Issue by marcopizzolato-mp** [binokochumolvarghese/lightbi-hugo#63]
Hello Bino, 

while using the template I have the following warning: 

`WARN  The author key in site configuration is deprecated. Use params.author.name instead.
`
I found this discussion: 
https://discourse.gohugo.io/t/new-warning-the-author-key-in-site-configuration-is-deprecated-use-params-author-name-instead/47034

and this similar opened issue in another template: 
https://github.com/jpanther/congo/issues/690

Many thanks

**Comment by binokochumolvarghese** [comment]
This issue has been solved. Please pull the latest version.
