### ISSUE TITLE
Language switch

### ISSUE THREAD

**Issue by FLeven** [binokochumolvarghese/lightbi-hugo#65]
I followed the wiki article and managed to setup a site with two languages and it worked very well. 

Is there an UI element I can make visible to let a visitor switch between languages on the site, instead of changing the URL from EN to DE etc. ?

**Comment by binokochumolvarghese** [comment]
Currently no, I will try to add in the future.

**Comment by binokochumolvarghese** [comment]
Added the language switch in the theme.
