### ISSUE TITLE
Deprecation error .Site.LastChange

### ISSUE THREAD

**Issue by jamesanderson9182** [binokochumolvarghese/lightbi-hugo#71]
Hi there,

I followed the instructions on your wiki and I ran into this error:

```
hugo v0.136.2+extended darwin/amd64 BuildDate=2024-10-17T14:30:05Z VendorInfo=brew

ERROR deprecated: .Site.LastChange was deprecated in Hugo v0.123.0 and will be removed in Hugo 0.137.0. Use .Site.Lastmod instead.
Built in 109 ms
Error: error building site: logged 1 error(s)
```

I'm new to Hugo. I tried just removing references to that in the `themes/lightbi-hugo` folder BUT I know that's not really the fix as I believe something needs changed properly on your end. 

If you can point me in the right direction, I'm happy to submit a PR

**Comment by binokochumolvarghese** [comment]
Hi,
I have updated the theme. Please pull the latest theme and try. If any issues let me know.

**Comment by jamesanderson9182** [comment]
HI @binokochumolvarghese , yes that fixed it. Thank you for your speedy update!
