### ISSUE TITLE
Installation instructions incomplete: no menu

### ISSUE THREAD

**Issue by FiableDotBiz** [binokochumolvarghese/lightbi-hugo#72]
I'm on Fedora 39 Workstation. The "Installation" [instructions](https://github.com/binokochumolvarghese/lightbi-hugo) don't work. The homepage (http://localhost:1313) is empty after that. I had to stop hugo (Ctrl-C) and to relaunch it in order to get the cards in the homepage. But there is still no menu and I don't know how to get it.

**Comment by binokochumolvarghese** [comment]
You may please check the demo website [here](https://github.com/binokochumolvarghese/lightbi-hugo-demo).

**Comment by FiableDotBiz** [comment]
But seeing the demo website will not correct the instructions...

**Comment by FiableDotBiz** [comment]
Thank you for your answer. Of course I didn't. It was not in the instructions.
